name: Deploy Website

run-name: Deploy Website

on:
  push:
    branches:
      - master
    paths:
      - '**.ex'
      - '**.exs'
      - 'mix.exs'
      - 'mix.lock'
      - '**/*.md'
      - '.github/workflows/deploy-website.yml'

jobs:
  deploy:
    name: ğŸš€ Deploy Website
    runs-on: ubuntu-22.04 # ubuntu-latest have issues on gituhb actions
    timeout-minutes: 30
    steps:
    - name: ğŸ“¥ Checkout repository
      uses: actions/checkout@v4

    - name: ğŸ”§ Set up Elixir
      uses: erlef/setup-beam@61e01a43a562a89bfc54c7f9a378ff67b03e4a21 # v1.16.0
      with:
        elixir-version: '1.17.2' # [Required] Define the Elixir version
        otp-version: '26.0'      # [Required] Define the Erlang/OTP version

    - name: ğŸ’¾ Restore dependencies cache
      uses: actions/cache@v3
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-

    - name: ğŸ“¦ Install dependencies
      run: mix deps.get

    - name: ğŸ”¨ Build Website
      run: mix docs
      
    - name: ğŸŒ Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./doc
